baseurl = "https://pixelspa.com/"
languageCode = "en-gb"
title = "Pixel Spa"
disableRSS = true
googleAnalytics = "UA-77433325-1"

[params]
  name = "Pixel Spa"
  description = "Beautiful UX/UI design for tech startups, agencies and growing businesses."
  # The path must be relative to the static folder
  favicon = "img/pixelfaccia.ico"
