baseurl = "https://pixelspa.com/"
languageCode = "en-gb"
title = "Pixel Spa"
disableRSS = true


[params]
  name = "Pixel Spa"
  description = "UI/UX agency"
  # The path must be relative to the static folder
  favicon = "img/pixelfaccia.ico"
